version: 2.1

aliases:
  - &docker-node
    - image: cimg/node:18.20.0

  - &restore-node-modules-cache
    name: Restore node_modules cache
    key: yarn-deps-{{ checksum "yarn.lock" }}

  - &restore-yarn-cache
    name: Restore yarnpkg cache
    key: yarn-cache

  - &save-node-modules-cache
    name: Save node_modules cache
    paths:
      - node_modules
    key: yarn-deps-{{ checksum "yarn.lock" }}

  - &save-yarn-cache
    name: Save yarnpkg cache
    paths:
      - ~/.cache/yarn
    key: yarn-cache

jobs:
  checkout-code:
    docker: *docker-node
    steps:
      - checkout
      - run: node --version
      - restore_cache: *restore-yarn-cache
      - restore_cache: *restore-node-modules-cache
      - run:
          no_output_timeout: 20m
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache: *save-node-modules-cache
      - save_cache: *save-yarn-cache
      - persist_to_workspace:
          root: "."
          paths: [
            packages/*/node_modules
          ]

  lint:
    docker: *docker-node
    steps:
      - checkout
      - restore_cache: *restore-node-modules-cache
      - attach_workspace: { at: "." }
      - run: yarn lint

  test:
    docker: *docker-node
    steps:
      - checkout
      - restore_cache: *restore-node-modules-cache
      - attach_workspace: { at: "." }
      - run: yarn test

  build:
    docker: *docker-node
    steps:
      - checkout
      - restore_cache: *restore-node-modules-cache
      - attach_workspace: { at: "." }
      - run: yarn build
      - persist_to_workspace:
          root: "."
          paths: [
            packages/*/dist,
            packages/webcomponents/www,
          ]

  deploy:
    docker: *docker-node
    steps:
      - checkout
      - restore_cache: *restore-node-modules-cache
      - attach_workspace: { at: "." }
      - run: |
          git config user.email "$GH_EMAIL"
          git config user.name "$GH_NAME"
          cd packages/webcomponents
          yarn deploy:gh-pages

workflows:
  version: 2
  compile_lint_test_dist_deploy:
    jobs:
      - checkout-code
      - lint:
          requires:
            - checkout-code
      - test:
          requires:
            - lint
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
