version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.20.4
    working_directory: ~/repo

jobs:
  install:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-v1-{{ checksum "yarn.lock" }}
            - yarn-v1-
      - run:
          name: Install dependencies
          no_output_timeout: 20m
          command: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - ~/.cache/yarn
            - node_modules
          key: yarn-v1-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  lint:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run linter
          command: yarn lint

  test:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: yarn test

  build:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build project
          command: yarn build

  deploy:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: |
          git config user.email "$GH_EMAIL"
          git config user.name "$GH_NAME"
          cd packages/webcomponents
          yarn deploy:gh-pages

workflows:
  version: 2
  install-lint-test-build:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - build:
          requires:
            - test
            - lint
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
