'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type PeculiarCertificatesViewerCustomEvent, type X509Certificate } from "@peculiar/certificates-viewer";
import type { Components } from "@peculiar/certificates-viewer/components";
import { PeculiarAttributeCertificateViewer as PeculiarAttributeCertificateViewerElement, defineCustomElement as definePeculiarAttributeCertificateViewer } from "@peculiar/certificates-viewer/components/peculiar-attribute-certificate-viewer.js";
import { PeculiarCertificateChainViewer as PeculiarCertificateChainViewerElement, defineCustomElement as definePeculiarCertificateChainViewer } from "@peculiar/certificates-viewer/components/peculiar-certificate-chain-viewer.js";
import { PeculiarCertificateViewer as PeculiarCertificateViewerElement, defineCustomElement as definePeculiarCertificateViewer } from "@peculiar/certificates-viewer/components/peculiar-certificate-viewer.js";
import { PeculiarCertificatesViewer as PeculiarCertificatesViewerElement, defineCustomElement as definePeculiarCertificatesViewer } from "@peculiar/certificates-viewer/components/peculiar-certificates-viewer.js";
import { PeculiarCrlViewer as PeculiarCrlViewerElement, defineCustomElement as definePeculiarCrlViewer } from "@peculiar/certificates-viewer/components/peculiar-crl-viewer.js";
import { PeculiarCsrViewer as PeculiarCsrViewerElement, defineCustomElement as definePeculiarCsrViewer } from "@peculiar/certificates-viewer/components/peculiar-csr-viewer.js";
import { PeculiarSshCertificateViewer as PeculiarSshCertificateViewerElement, defineCustomElement as definePeculiarSshCertificateViewer } from "@peculiar/certificates-viewer/components/peculiar-ssh-certificate-viewer.js";

export type PeculiarAttributeCertificateViewerEvents = NonNullable<unknown>;

export const PeculiarAttributeCertificateViewer: StencilReactComponent<PeculiarAttributeCertificateViewerElement, PeculiarAttributeCertificateViewerEvents, Components.PeculiarAttributeCertificateViewer> = /*@__PURE__*/ createComponent<PeculiarAttributeCertificateViewerElement, PeculiarAttributeCertificateViewerEvents, Components.PeculiarAttributeCertificateViewer>({
    tagName: 'peculiar-attribute-certificate-viewer',
    elementClass: PeculiarAttributeCertificateViewerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as PeculiarAttributeCertificateViewerEvents,
    defineCustomElement: definePeculiarAttributeCertificateViewer
});

export type PeculiarCertificateChainViewerEvents = NonNullable<unknown>;

export const PeculiarCertificateChainViewer: StencilReactComponent<PeculiarCertificateChainViewerElement, PeculiarCertificateChainViewerEvents, Components.PeculiarCertificateChainViewer> = /*@__PURE__*/ createComponent<PeculiarCertificateChainViewerElement, PeculiarCertificateChainViewerEvents, Components.PeculiarCertificateChainViewer>({
    tagName: 'peculiar-certificate-chain-viewer',
    elementClass: PeculiarCertificateChainViewerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as PeculiarCertificateChainViewerEvents,
    defineCustomElement: definePeculiarCertificateChainViewer
});

export type PeculiarCertificateViewerEvents = NonNullable<unknown>;

export const PeculiarCertificateViewer: StencilReactComponent<PeculiarCertificateViewerElement, PeculiarCertificateViewerEvents, Components.PeculiarCertificateViewer> = /*@__PURE__*/ createComponent<PeculiarCertificateViewerElement, PeculiarCertificateViewerEvents, Components.PeculiarCertificateViewer>({
    tagName: 'peculiar-certificate-viewer',
    elementClass: PeculiarCertificateViewerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as PeculiarCertificateViewerEvents,
    defineCustomElement: definePeculiarCertificateViewer
});

export type PeculiarCertificatesViewerEvents = {
    onDetailsOpen: EventName<PeculiarCertificatesViewerCustomEvent<X509Certificate>>,
    onDetailsClose: EventName<PeculiarCertificatesViewerCustomEvent<void>>
};

export const PeculiarCertificatesViewer: StencilReactComponent<PeculiarCertificatesViewerElement, PeculiarCertificatesViewerEvents, Components.PeculiarCertificatesViewer> = /*@__PURE__*/ createComponent<PeculiarCertificatesViewerElement, PeculiarCertificatesViewerEvents, Components.PeculiarCertificatesViewer>({
    tagName: 'peculiar-certificates-viewer',
    elementClass: PeculiarCertificatesViewerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onDetailsOpen: 'detailsOpen',
        onDetailsClose: 'detailsClose'
    } as PeculiarCertificatesViewerEvents,
    defineCustomElement: definePeculiarCertificatesViewer
});

export type PeculiarCrlViewerEvents = NonNullable<unknown>;

export const PeculiarCrlViewer: StencilReactComponent<PeculiarCrlViewerElement, PeculiarCrlViewerEvents, Components.PeculiarCrlViewer> = /*@__PURE__*/ createComponent<PeculiarCrlViewerElement, PeculiarCrlViewerEvents, Components.PeculiarCrlViewer>({
    tagName: 'peculiar-crl-viewer',
    elementClass: PeculiarCrlViewerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as PeculiarCrlViewerEvents,
    defineCustomElement: definePeculiarCrlViewer
});

export type PeculiarCsrViewerEvents = NonNullable<unknown>;

export const PeculiarCsrViewer: StencilReactComponent<PeculiarCsrViewerElement, PeculiarCsrViewerEvents, Components.PeculiarCsrViewer> = /*@__PURE__*/ createComponent<PeculiarCsrViewerElement, PeculiarCsrViewerEvents, Components.PeculiarCsrViewer>({
    tagName: 'peculiar-csr-viewer',
    elementClass: PeculiarCsrViewerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as PeculiarCsrViewerEvents,
    defineCustomElement: definePeculiarCsrViewer
});

export type PeculiarSshCertificateViewerEvents = NonNullable<unknown>;

export const PeculiarSshCertificateViewer: StencilReactComponent<PeculiarSshCertificateViewerElement, PeculiarSshCertificateViewerEvents, Components.PeculiarSshCertificateViewer> = /*@__PURE__*/ createComponent<PeculiarSshCertificateViewerElement, PeculiarSshCertificateViewerEvents, Components.PeculiarSshCertificateViewer>({
    tagName: 'peculiar-ssh-certificate-viewer',
    elementClass: PeculiarSshCertificateViewerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as PeculiarSshCertificateViewerEvents,
    defineCustomElement: definePeculiarSshCertificateViewer
});
