/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface PvCertificateViewer {
    'certificate': string;
  }
  interface PvCertificatesViewer {
    'certificates': string;
  }
  interface PvInput {
    'class': string;
    'onChange': (event: Event) => void;
    'onInput': (event: Event) => void;
    'placeholder': string;
  }
}

declare global {


  interface HTMLPvCertificateViewerElement extends Components.PvCertificateViewer, HTMLStencilElement {}
  var HTMLPvCertificateViewerElement: {
    prototype: HTMLPvCertificateViewerElement;
    new (): HTMLPvCertificateViewerElement;
  };

  interface HTMLPvCertificatesViewerElement extends Components.PvCertificatesViewer, HTMLStencilElement {}
  var HTMLPvCertificatesViewerElement: {
    prototype: HTMLPvCertificatesViewerElement;
    new (): HTMLPvCertificatesViewerElement;
  };

  interface HTMLPvInputElement extends Components.PvInput, HTMLStencilElement {}
  var HTMLPvInputElement: {
    prototype: HTMLPvInputElement;
    new (): HTMLPvInputElement;
  };
  interface HTMLElementTagNameMap {
    'pv-certificate-viewer': HTMLPvCertificateViewerElement;
    'pv-certificates-viewer': HTMLPvCertificatesViewerElement;
    'pv-input': HTMLPvInputElement;
  }
}

declare namespace LocalJSX {
  interface PvCertificateViewer {
    'certificate'?: string;
  }
  interface PvCertificatesViewer {
    'certificates'?: string;
  }
  interface PvInput {
    'class'?: string;
    'onChange'?: (event: Event) => void;
    'onInput'?: (event: Event) => void;
    'placeholder'?: string;
  }

  interface IntrinsicElements {
    'pv-certificate-viewer': PvCertificateViewer;
    'pv-certificates-viewer': PvCertificatesViewer;
    'pv-input': PvInput;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'pv-certificate-viewer': LocalJSX.PvCertificateViewer & JSXBase.HTMLAttributes<HTMLPvCertificateViewerElement>;
      'pv-certificates-viewer': LocalJSX.PvCertificatesViewer & JSXBase.HTMLAttributes<HTMLPvCertificatesViewerElement>;
      'pv-input': LocalJSX.PvInput & JSXBase.HTMLAttributes<HTMLPvInputElement>;
    }
  }
}


