/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TAttributeCertificateProp } from "./components/attribute-certificate-viewer/attribute-certificate-viewer";
import { IButtonMenuGroup } from "./components/button-menu/button-menu";
import { X509Certificate, X509Certificates } from "./crypto";
import { TCertificateProp } from "./components/certificate-viewer/certificate-viewer";
import { ICertificate } from "./components/certificates-viewer/certificates-viewer";
import { TCrlProp } from "./components/crl-viewer/crl-viewer";
import { TCsrProp } from "./components/csr-viewer/csr-viewer";
import { TSshCertificateProp } from "./components/ssh-certificate-viewer/ssh-certificate-viewer";
export { TAttributeCertificateProp } from "./components/attribute-certificate-viewer/attribute-certificate-viewer";
export { IButtonMenuGroup } from "./components/button-menu/button-menu";
export { X509Certificate, X509Certificates } from "./crypto";
export { TCertificateProp } from "./components/certificate-viewer/certificate-viewer";
export { ICertificate } from "./components/certificates-viewer/certificates-viewer";
export { TCrlProp } from "./components/crl-viewer/crl-viewer";
export { TCsrProp } from "./components/csr-viewer/csr-viewer";
export { TSshCertificateProp } from "./components/ssh-certificate-viewer/ssh-certificate-viewer";
export namespace Components {
    interface PeculiarAttributeCertificateViewer {
        /**
          * Authority Key Identifier extension parent link. <br /> **NOTE**: `{{authKeyId}}` will be replaced to value from the extension.
          * @example  https://censys.io/certificates?q=parsed.extensions.subject_key_id:%20{{authKeyId}}
         */
        "authKeyIdParentLink"?: string;
        /**
          * Authority Key Identifier extension siblings link. <br /> **NOTE**: `{{authKeyId}}` will be replaced to value from the extension.
          * @example  https://censys.io/certificates?q=parsed.extensions.authority_key_id:%20{{authKeyId}}
         */
        "authKeyIdSiblingsLink"?: string;
        /**
          * The certificate value for decode and show details. Use PEM or DER.
         */
        "certificate": TAttributeCertificateProp;
        /**
          * If `true` - component will show split-button to download certificate as PEM or DER.
         */
        "download"?: boolean;
        /**
          * Mobile media query string to control screen view change. <br /> **NOTE**: Based on https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia.
          * @example  (max-width: 900px)
          * @default '(max-width: 900px)'
         */
        "mobileMediaQueryString"?: string;
        /**
          * Subject Key Identifier extension children link. <br /> **NOTE**: `{{subjectKeyId}}` will be replaced to value from the extension.
          * @example  https://censys.io/certificates?q=parsed.extensions.authority_key_id:%20{{subjectKeyId}}
         */
        "subjectKeyIdChildrenLink"?: string;
        /**
          * Subject Key Identifier extension siblings link. <br /> **NOTE**: `{{subjectKeyId}}` will be replaced to value from the extension.
          * @example  https://some.com/{{subjectKeyId}}
         */
        "subjectKeyIdSiblingsLink"?: string;
    }
    interface PeculiarButtonMenu {
        /**
          * @default []
         */
        "groups": IButtonMenuGroup[];
    }
    interface PeculiarCertificateChainViewer {
        /**
          * The certificate value for decode and show details. Use PEM or DER.
         */
        "certificates": X509Certificates;
        /**
          * If `true` - component will show split-button to download certificate as PEM or DER.
         */
        "download"?: boolean;
    }
    interface PeculiarCertificateDecoder {
        /**
          * Pre-loaded example certificates available in the "Load example" dropdown.
         */
        "certificateExamples"?: {
    title: string;
    value: string;
  }[];
        /**
          * A certificate to decode on first load (PEM or Base64 DER).
         */
        "certificateToDecode"?: string;
    }
    interface PeculiarCertificateViewer {
        /**
          * Authority Key Identifier extension parent link. <br /> **NOTE**: `{{authKeyId}}` will be replaced to value from the extension.
          * @example  https://censys.io/certificates?q=parsed.extensions.subject_key_id:%20{{authKeyId}}
         */
        "authKeyIdParentLink"?: string;
        /**
          * Authority Key Identifier extension siblings link. <br /> **NOTE**: `{{authKeyId}}` will be replaced to value from the extension.
          * @example  https://censys.io/certificates?q=parsed.extensions.authority_key_id:%20{{authKeyId}}
         */
        "authKeyIdSiblingsLink"?: string;
        /**
          * The certificate value for decode and show details. Use PEM or DER.
         */
        "certificate": TCertificateProp;
        /**
          * If `true` - component will show split-button to download certificate as PEM or DER.
         */
        "download"?: boolean;
        /**
          * Issuer DN link. **NOTE**: HTML component attribute must be `issuer-dn-link`.
         */
        "issuerDnLink"?: string;
        /**
          * Mobile media query string to control screen view change. <br /> **NOTE**: Based on https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia.
          * @example  (max-width: 900px)
          * @default '(max-width: 900px)'
         */
        "mobileMediaQueryString"?: string;
        /**
          * Subject Key Identifier extension children link. <br /> **NOTE**: `{{subjectKeyId}}` will be replaced to value from the extension.
          * @example  https://censys.io/certificates?q=parsed.extensions.authority_key_id:%20{{subjectKeyId}}
         */
        "subjectKeyIdChildrenLink"?: string;
        /**
          * Subject Key Identifier extension siblings link. <br /> **NOTE**: `{{subjectKeyId}}` will be replaced to value from the extension.
          * @example  https://some.com/{{subjectKeyId}}
         */
        "subjectKeyIdSiblingsLink"?: string;
    }
    interface PeculiarCertificatesViewer {
        /**
          * List of certificates values for decode and show in the list. <br /> **NOTE**: If you do not provide a `name` value when invocing the component it will take the first Subject CN value. <br /> **NOTE**: If you do not provide a `tests` this column will be ommited from the rendered page. <br /> **NOTE**: If the supplied certificates are self-signed the issuer column will be ommited.
          * @default []
         */
        "certificates": ICertificate[];
        /**
          * Use filter in the list when search is changed.
          * @default true
         */
        "filterWithSearch": boolean;
        /**
          * Use highlight chapters in the list when search is changed.
          * @default true
         */
        "highlightWithSearch": boolean;
        /**
          * Mobile media query string to control screen view change. <br /> **NOTE**: Based on https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia.
          * @example  (max-width: 900px)
          * @default '(max-width: 900px)'
         */
        "mobileMediaQueryString"?: string;
    }
    interface PeculiarCircularProgress {
        /**
          * Width/height of progress circle.
          * @default 24
         */
        "size": number;
        /**
          * Stroke width of progress bar circle.
          * @default 4
         */
        "width": number;
    }
    interface PeculiarCrlViewer {
        /**
          * Authority Key Identifier extension parent link. <br /> **NOTE**: `{{authKeyId}}` will be replaced to value from the extension.
          * @example  https://censys.io/certificates?q=parsed.extensions.subject_key_id:%20{{authKeyId}}
         */
        "authKeyIdParentLink"?: string;
        /**
          * Authority Key Identifier extension siblings link. <br /> **NOTE**: `{{authKeyId}}` will be replaced to value from the extension.
          * @example  https://censys.io/certificates?q=parsed.extensions.authority_key_id:%20{{authKeyId}}
         */
        "authKeyIdSiblingsLink"?: string;
        /**
          * The certificate value for decode and show details. Use PEM or DER.
         */
        "certificate": TCrlProp;
        /**
          * If `true` - component will show split-button to download certificate as PEM or DER.
         */
        "download"?: boolean;
        /**
          * Issuer DN link. **NOTE**: HTML component attribute must be `issuer-dn-link`.
         */
        "issuerDnLink"?: string;
        /**
          * Mobile media query string to control screen view change. <br /> **NOTE**: Based on https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia.
          * @example  (max-width: 900px)
          * @default '(max-width: 900px)'
         */
        "mobileMediaQueryString"?: string;
    }
    interface PeculiarCsrViewer {
        /**
          * The certificate value for decode and show details. Use PEM or DER.
         */
        "certificate": TCsrProp;
        /**
          * If `true` - component will show split-button to download certificate as PEM or DER.
         */
        "download"?: boolean;
        /**
          * Mobile media query string to control screen view change. <br /> **NOTE**: Based on https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia.
          * @example  (max-width: 900px)
          * @default '(max-width: 900px)'
         */
        "mobileMediaQueryString"?: string;
        /**
          * Subject Key Identifier extension children link. <br /> **NOTE**: `{{subjectKeyId}}` will be replaced to value from the extension.
          * @example  https://censys.io/certificates?q=parsed.extensions.authority_key_id:%20{{subjectKeyId}}
         */
        "subjectKeyIdChildrenLink"?: string;
        /**
          * Subject Key Identifier extension siblings link. <br /> **NOTE**: `{{subjectKeyId}}` will be replaced to value from the extension.
          * @example  https://some.com/{{subjectKeyId}}
         */
        "subjectKeyIdSiblingsLink"?: string;
    }
    interface PeculiarHighlightWords {
        "search": string;
    }
    interface PeculiarSshCertificateViewer {
        /**
          * The certificate value for decode and show details. Use PEM or DER.
         */
        "certificate": TSshCertificateProp;
        /**
          * If `true` - component will show split-button to download certificate as PEM or DER.
         */
        "download"?: boolean;
        /**
          * Mobile media query string to control screen view change. <br /> **NOTE**: Based on https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia.
          * @example  (max-width: 900px)
          * @default '(max-width: 900px)'
         */
        "mobileMediaQueryString"?: string;
    }
    interface PeculiarTextHider {
    }
}
export interface PeculiarCertificateDecoderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPeculiarCertificateDecoderElement;
}
export interface PeculiarCertificatesViewerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPeculiarCertificatesViewerElement;
}
declare global {
    interface HTMLPeculiarAttributeCertificateViewerElement extends Components.PeculiarAttributeCertificateViewer, HTMLStencilElement {
    }
    var HTMLPeculiarAttributeCertificateViewerElement: {
        prototype: HTMLPeculiarAttributeCertificateViewerElement;
        new (): HTMLPeculiarAttributeCertificateViewerElement;
    };
    interface HTMLPeculiarButtonMenuElement extends Components.PeculiarButtonMenu, HTMLStencilElement {
    }
    var HTMLPeculiarButtonMenuElement: {
        prototype: HTMLPeculiarButtonMenuElement;
        new (): HTMLPeculiarButtonMenuElement;
    };
    interface HTMLPeculiarCertificateChainViewerElement extends Components.PeculiarCertificateChainViewer, HTMLStencilElement {
    }
    var HTMLPeculiarCertificateChainViewerElement: {
        prototype: HTMLPeculiarCertificateChainViewerElement;
        new (): HTMLPeculiarCertificateChainViewerElement;
    };
    interface HTMLPeculiarCertificateDecoderElementEventMap {
        "successParse": string;
        "clearCertificate": void;
    }
    interface HTMLPeculiarCertificateDecoderElement extends Components.PeculiarCertificateDecoder, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPeculiarCertificateDecoderElementEventMap>(type: K, listener: (this: HTMLPeculiarCertificateDecoderElement, ev: PeculiarCertificateDecoderCustomEvent<HTMLPeculiarCertificateDecoderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPeculiarCertificateDecoderElementEventMap>(type: K, listener: (this: HTMLPeculiarCertificateDecoderElement, ev: PeculiarCertificateDecoderCustomEvent<HTMLPeculiarCertificateDecoderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPeculiarCertificateDecoderElement: {
        prototype: HTMLPeculiarCertificateDecoderElement;
        new (): HTMLPeculiarCertificateDecoderElement;
    };
    interface HTMLPeculiarCertificateViewerElement extends Components.PeculiarCertificateViewer, HTMLStencilElement {
    }
    var HTMLPeculiarCertificateViewerElement: {
        prototype: HTMLPeculiarCertificateViewerElement;
        new (): HTMLPeculiarCertificateViewerElement;
    };
    interface HTMLPeculiarCertificatesViewerElementEventMap {
        "detailsOpen": X509Certificate;
        "detailsClose": void;
    }
    interface HTMLPeculiarCertificatesViewerElement extends Components.PeculiarCertificatesViewer, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPeculiarCertificatesViewerElementEventMap>(type: K, listener: (this: HTMLPeculiarCertificatesViewerElement, ev: PeculiarCertificatesViewerCustomEvent<HTMLPeculiarCertificatesViewerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPeculiarCertificatesViewerElementEventMap>(type: K, listener: (this: HTMLPeculiarCertificatesViewerElement, ev: PeculiarCertificatesViewerCustomEvent<HTMLPeculiarCertificatesViewerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPeculiarCertificatesViewerElement: {
        prototype: HTMLPeculiarCertificatesViewerElement;
        new (): HTMLPeculiarCertificatesViewerElement;
    };
    interface HTMLPeculiarCircularProgressElement extends Components.PeculiarCircularProgress, HTMLStencilElement {
    }
    var HTMLPeculiarCircularProgressElement: {
        prototype: HTMLPeculiarCircularProgressElement;
        new (): HTMLPeculiarCircularProgressElement;
    };
    interface HTMLPeculiarCrlViewerElement extends Components.PeculiarCrlViewer, HTMLStencilElement {
    }
    var HTMLPeculiarCrlViewerElement: {
        prototype: HTMLPeculiarCrlViewerElement;
        new (): HTMLPeculiarCrlViewerElement;
    };
    interface HTMLPeculiarCsrViewerElement extends Components.PeculiarCsrViewer, HTMLStencilElement {
    }
    var HTMLPeculiarCsrViewerElement: {
        prototype: HTMLPeculiarCsrViewerElement;
        new (): HTMLPeculiarCsrViewerElement;
    };
    interface HTMLPeculiarHighlightWordsElement extends Components.PeculiarHighlightWords, HTMLStencilElement {
    }
    var HTMLPeculiarHighlightWordsElement: {
        prototype: HTMLPeculiarHighlightWordsElement;
        new (): HTMLPeculiarHighlightWordsElement;
    };
    interface HTMLPeculiarSshCertificateViewerElement extends Components.PeculiarSshCertificateViewer, HTMLStencilElement {
    }
    var HTMLPeculiarSshCertificateViewerElement: {
        prototype: HTMLPeculiarSshCertificateViewerElement;
        new (): HTMLPeculiarSshCertificateViewerElement;
    };
    interface HTMLPeculiarTextHiderElement extends Components.PeculiarTextHider, HTMLStencilElement {
    }
    var HTMLPeculiarTextHiderElement: {
        prototype: HTMLPeculiarTextHiderElement;
        new (): HTMLPeculiarTextHiderElement;
    };
    interface HTMLElementTagNameMap {
        "peculiar-attribute-certificate-viewer": HTMLPeculiarAttributeCertificateViewerElement;
        "peculiar-button-menu": HTMLPeculiarButtonMenuElement;
        "peculiar-certificate-chain-viewer": HTMLPeculiarCertificateChainViewerElement;
        "peculiar-certificate-decoder": HTMLPeculiarCertificateDecoderElement;
        "peculiar-certificate-viewer": HTMLPeculiarCertificateViewerElement;
        "peculiar-certificates-viewer": HTMLPeculiarCertificatesViewerElement;
        "peculiar-circular-progress": HTMLPeculiarCircularProgressElement;
        "peculiar-crl-viewer": HTMLPeculiarCrlViewerElement;
        "peculiar-csr-viewer": HTMLPeculiarCsrViewerElement;
        "peculiar-highlight-words": HTMLPeculiarHighlightWordsElement;
        "peculiar-ssh-certificate-viewer": HTMLPeculiarSshCertificateViewerElement;
        "peculiar-text-hider": HTMLPeculiarTextHiderElement;
    }
}
declare namespace LocalJSX {
    interface PeculiarAttributeCertificateViewer {
        /**
          * Authority Key Identifier extension parent link. <br /> **NOTE**: `{{authKeyId}}` will be replaced to value from the extension.
          * @example  https://censys.io/certificates?q=parsed.extensions.subject_key_id:%20{{authKeyId}}
         */
        "authKeyIdParentLink"?: string;
        /**
          * Authority Key Identifier extension siblings link. <br /> **NOTE**: `{{authKeyId}}` will be replaced to value from the extension.
          * @example  https://censys.io/certificates?q=parsed.extensions.authority_key_id:%20{{authKeyId}}
         */
        "authKeyIdSiblingsLink"?: string;
        /**
          * The certificate value for decode and show details. Use PEM or DER.
         */
        "certificate"?: TAttributeCertificateProp;
        /**
          * If `true` - component will show split-button to download certificate as PEM or DER.
         */
        "download"?: boolean;
        /**
          * Mobile media query string to control screen view change. <br /> **NOTE**: Based on https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia.
          * @example  (max-width: 900px)
          * @default '(max-width: 900px)'
         */
        "mobileMediaQueryString"?: string;
        /**
          * Subject Key Identifier extension children link. <br /> **NOTE**: `{{subjectKeyId}}` will be replaced to value from the extension.
          * @example  https://censys.io/certificates?q=parsed.extensions.authority_key_id:%20{{subjectKeyId}}
         */
        "subjectKeyIdChildrenLink"?: string;
        /**
          * Subject Key Identifier extension siblings link. <br /> **NOTE**: `{{subjectKeyId}}` will be replaced to value from the extension.
          * @example  https://some.com/{{subjectKeyId}}
         */
        "subjectKeyIdSiblingsLink"?: string;
    }
    interface PeculiarButtonMenu {
        /**
          * @default []
         */
        "groups"?: IButtonMenuGroup[];
    }
    interface PeculiarCertificateChainViewer {
        /**
          * The certificate value for decode and show details. Use PEM or DER.
         */
        "certificates"?: X509Certificates;
        /**
          * If `true` - component will show split-button to download certificate as PEM or DER.
         */
        "download"?: boolean;
    }
    interface PeculiarCertificateDecoder {
        /**
          * Pre-loaded example certificates available in the "Load example" dropdown.
         */
        "certificateExamples"?: {
    title: string;
    value: string;
  }[];
        /**
          * A certificate to decode on first load (PEM or Base64 DER).
         */
        "certificateToDecode"?: string;
        /**
          * Emitted when the input has been cleared.
         */
        "onClearCertificate"?: (event: PeculiarCertificateDecoderCustomEvent<void>) => void;
        /**
          * Emitted when a certificate has been successfully parsed.
         */
        "onSuccessParse"?: (event: PeculiarCertificateDecoderCustomEvent<string>) => void;
    }
    interface PeculiarCertificateViewer {
        /**
          * Authority Key Identifier extension parent link. <br /> **NOTE**: `{{authKeyId}}` will be replaced to value from the extension.
          * @example  https://censys.io/certificates?q=parsed.extensions.subject_key_id:%20{{authKeyId}}
         */
        "authKeyIdParentLink"?: string;
        /**
          * Authority Key Identifier extension siblings link. <br /> **NOTE**: `{{authKeyId}}` will be replaced to value from the extension.
          * @example  https://censys.io/certificates?q=parsed.extensions.authority_key_id:%20{{authKeyId}}
         */
        "authKeyIdSiblingsLink"?: string;
        /**
          * The certificate value for decode and show details. Use PEM or DER.
         */
        "certificate"?: TCertificateProp;
        /**
          * If `true` - component will show split-button to download certificate as PEM or DER.
         */
        "download"?: boolean;
        /**
          * Issuer DN link. **NOTE**: HTML component attribute must be `issuer-dn-link`.
         */
        "issuerDnLink"?: string;
        /**
          * Mobile media query string to control screen view change. <br /> **NOTE**: Based on https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia.
          * @example  (max-width: 900px)
          * @default '(max-width: 900px)'
         */
        "mobileMediaQueryString"?: string;
        /**
          * Subject Key Identifier extension children link. <br /> **NOTE**: `{{subjectKeyId}}` will be replaced to value from the extension.
          * @example  https://censys.io/certificates?q=parsed.extensions.authority_key_id:%20{{subjectKeyId}}
         */
        "subjectKeyIdChildrenLink"?: string;
        /**
          * Subject Key Identifier extension siblings link. <br /> **NOTE**: `{{subjectKeyId}}` will be replaced to value from the extension.
          * @example  https://some.com/{{subjectKeyId}}
         */
        "subjectKeyIdSiblingsLink"?: string;
    }
    interface PeculiarCertificatesViewer {
        /**
          * List of certificates values for decode and show in the list. <br /> **NOTE**: If you do not provide a `name` value when invocing the component it will take the first Subject CN value. <br /> **NOTE**: If you do not provide a `tests` this column will be ommited from the rendered page. <br /> **NOTE**: If the supplied certificates are self-signed the issuer column will be ommited.
          * @default []
         */
        "certificates"?: ICertificate[];
        /**
          * Use filter in the list when search is changed.
          * @default true
         */
        "filterWithSearch"?: boolean;
        /**
          * Use highlight chapters in the list when search is changed.
          * @default true
         */
        "highlightWithSearch"?: boolean;
        /**
          * Mobile media query string to control screen view change. <br /> **NOTE**: Based on https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia.
          * @example  (max-width: 900px)
          * @default '(max-width: 900px)'
         */
        "mobileMediaQueryString"?: string;
        /**
          * Emitted when the user close certificate details modal.
         */
        "onDetailsClose"?: (event: PeculiarCertificatesViewerCustomEvent<void>) => void;
        /**
          * Emitted when the user open certificate details modal.
         */
        "onDetailsOpen"?: (event: PeculiarCertificatesViewerCustomEvent<X509Certificate>) => void;
    }
    interface PeculiarCircularProgress {
        /**
          * Width/height of progress circle.
          * @default 24
         */
        "size"?: number;
        /**
          * Stroke width of progress bar circle.
          * @default 4
         */
        "width"?: number;
    }
    interface PeculiarCrlViewer {
        /**
          * Authority Key Identifier extension parent link. <br /> **NOTE**: `{{authKeyId}}` will be replaced to value from the extension.
          * @example  https://censys.io/certificates?q=parsed.extensions.subject_key_id:%20{{authKeyId}}
         */
        "authKeyIdParentLink"?: string;
        /**
          * Authority Key Identifier extension siblings link. <br /> **NOTE**: `{{authKeyId}}` will be replaced to value from the extension.
          * @example  https://censys.io/certificates?q=parsed.extensions.authority_key_id:%20{{authKeyId}}
         */
        "authKeyIdSiblingsLink"?: string;
        /**
          * The certificate value for decode and show details. Use PEM or DER.
         */
        "certificate"?: TCrlProp;
        /**
          * If `true` - component will show split-button to download certificate as PEM or DER.
         */
        "download"?: boolean;
        /**
          * Issuer DN link. **NOTE**: HTML component attribute must be `issuer-dn-link`.
         */
        "issuerDnLink"?: string;
        /**
          * Mobile media query string to control screen view change. <br /> **NOTE**: Based on https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia.
          * @example  (max-width: 900px)
          * @default '(max-width: 900px)'
         */
        "mobileMediaQueryString"?: string;
    }
    interface PeculiarCsrViewer {
        /**
          * The certificate value for decode and show details. Use PEM or DER.
         */
        "certificate"?: TCsrProp;
        /**
          * If `true` - component will show split-button to download certificate as PEM or DER.
         */
        "download"?: boolean;
        /**
          * Mobile media query string to control screen view change. <br /> **NOTE**: Based on https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia.
          * @example  (max-width: 900px)
          * @default '(max-width: 900px)'
         */
        "mobileMediaQueryString"?: string;
        /**
          * Subject Key Identifier extension children link. <br /> **NOTE**: `{{subjectKeyId}}` will be replaced to value from the extension.
          * @example  https://censys.io/certificates?q=parsed.extensions.authority_key_id:%20{{subjectKeyId}}
         */
        "subjectKeyIdChildrenLink"?: string;
        /**
          * Subject Key Identifier extension siblings link. <br /> **NOTE**: `{{subjectKeyId}}` will be replaced to value from the extension.
          * @example  https://some.com/{{subjectKeyId}}
         */
        "subjectKeyIdSiblingsLink"?: string;
    }
    interface PeculiarHighlightWords {
        "search"?: string;
    }
    interface PeculiarSshCertificateViewer {
        /**
          * The certificate value for decode and show details. Use PEM or DER.
         */
        "certificate"?: TSshCertificateProp;
        /**
          * If `true` - component will show split-button to download certificate as PEM or DER.
         */
        "download"?: boolean;
        /**
          * Mobile media query string to control screen view change. <br /> **NOTE**: Based on https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia.
          * @example  (max-width: 900px)
          * @default '(max-width: 900px)'
         */
        "mobileMediaQueryString"?: string;
    }
    interface PeculiarTextHider {
    }

    interface PeculiarAttributeCertificateViewerAttributes {
        "certificate": TAttributeCertificateProp;
        "download": boolean;
        "authKeyIdParentLink": string;
        "authKeyIdSiblingsLink": string;
        "subjectKeyIdChildrenLink": string;
        "subjectKeyIdSiblingsLink": string;
        "mobileMediaQueryString": string;
    }
    interface PeculiarCertificateChainViewerAttributes {
        "download": boolean;
    }
    interface PeculiarCertificateDecoderAttributes {
        "certificateToDecode": string;
    }
    interface PeculiarCertificateViewerAttributes {
        "certificate": TCertificateProp;
        "download": boolean;
        "authKeyIdParentLink": string;
        "authKeyIdSiblingsLink": string;
        "subjectKeyIdChildrenLink": string;
        "subjectKeyIdSiblingsLink": string;
        "issuerDnLink": string;
        "mobileMediaQueryString": string;
    }
    interface PeculiarCertificatesViewerAttributes {
        "filterWithSearch": boolean;
        "highlightWithSearch": boolean;
        "mobileMediaQueryString": string;
    }
    interface PeculiarCircularProgressAttributes {
        "size": number;
        "width": number;
    }
    interface PeculiarCrlViewerAttributes {
        "certificate": TCrlProp;
        "download": boolean;
        "authKeyIdParentLink": string;
        "authKeyIdSiblingsLink": string;
        "issuerDnLink": string;
        "mobileMediaQueryString": string;
    }
    interface PeculiarCsrViewerAttributes {
        "certificate": TCsrProp;
        "download": boolean;
        "subjectKeyIdChildrenLink": string;
        "subjectKeyIdSiblingsLink": string;
        "mobileMediaQueryString": string;
    }
    interface PeculiarHighlightWordsAttributes {
        "search": string;
    }
    interface PeculiarSshCertificateViewerAttributes {
        "certificate": TSshCertificateProp;
        "download": boolean;
        "mobileMediaQueryString": string;
    }

    interface IntrinsicElements {
        "peculiar-attribute-certificate-viewer": Omit<PeculiarAttributeCertificateViewer, keyof PeculiarAttributeCertificateViewerAttributes> & { [K in keyof PeculiarAttributeCertificateViewer & keyof PeculiarAttributeCertificateViewerAttributes]?: PeculiarAttributeCertificateViewer[K] } & { [K in keyof PeculiarAttributeCertificateViewer & keyof PeculiarAttributeCertificateViewerAttributes as `attr:${K}`]?: PeculiarAttributeCertificateViewerAttributes[K] } & { [K in keyof PeculiarAttributeCertificateViewer & keyof PeculiarAttributeCertificateViewerAttributes as `prop:${K}`]?: PeculiarAttributeCertificateViewer[K] };
        "peculiar-button-menu": PeculiarButtonMenu;
        "peculiar-certificate-chain-viewer": Omit<PeculiarCertificateChainViewer, keyof PeculiarCertificateChainViewerAttributes> & { [K in keyof PeculiarCertificateChainViewer & keyof PeculiarCertificateChainViewerAttributes]?: PeculiarCertificateChainViewer[K] } & { [K in keyof PeculiarCertificateChainViewer & keyof PeculiarCertificateChainViewerAttributes as `attr:${K}`]?: PeculiarCertificateChainViewerAttributes[K] } & { [K in keyof PeculiarCertificateChainViewer & keyof PeculiarCertificateChainViewerAttributes as `prop:${K}`]?: PeculiarCertificateChainViewer[K] };
        "peculiar-certificate-decoder": Omit<PeculiarCertificateDecoder, keyof PeculiarCertificateDecoderAttributes> & { [K in keyof PeculiarCertificateDecoder & keyof PeculiarCertificateDecoderAttributes]?: PeculiarCertificateDecoder[K] } & { [K in keyof PeculiarCertificateDecoder & keyof PeculiarCertificateDecoderAttributes as `attr:${K}`]?: PeculiarCertificateDecoderAttributes[K] } & { [K in keyof PeculiarCertificateDecoder & keyof PeculiarCertificateDecoderAttributes as `prop:${K}`]?: PeculiarCertificateDecoder[K] };
        "peculiar-certificate-viewer": Omit<PeculiarCertificateViewer, keyof PeculiarCertificateViewerAttributes> & { [K in keyof PeculiarCertificateViewer & keyof PeculiarCertificateViewerAttributes]?: PeculiarCertificateViewer[K] } & { [K in keyof PeculiarCertificateViewer & keyof PeculiarCertificateViewerAttributes as `attr:${K}`]?: PeculiarCertificateViewerAttributes[K] } & { [K in keyof PeculiarCertificateViewer & keyof PeculiarCertificateViewerAttributes as `prop:${K}`]?: PeculiarCertificateViewer[K] };
        "peculiar-certificates-viewer": Omit<PeculiarCertificatesViewer, keyof PeculiarCertificatesViewerAttributes> & { [K in keyof PeculiarCertificatesViewer & keyof PeculiarCertificatesViewerAttributes]?: PeculiarCertificatesViewer[K] } & { [K in keyof PeculiarCertificatesViewer & keyof PeculiarCertificatesViewerAttributes as `attr:${K}`]?: PeculiarCertificatesViewerAttributes[K] } & { [K in keyof PeculiarCertificatesViewer & keyof PeculiarCertificatesViewerAttributes as `prop:${K}`]?: PeculiarCertificatesViewer[K] };
        "peculiar-circular-progress": Omit<PeculiarCircularProgress, keyof PeculiarCircularProgressAttributes> & { [K in keyof PeculiarCircularProgress & keyof PeculiarCircularProgressAttributes]?: PeculiarCircularProgress[K] } & { [K in keyof PeculiarCircularProgress & keyof PeculiarCircularProgressAttributes as `attr:${K}`]?: PeculiarCircularProgressAttributes[K] } & { [K in keyof PeculiarCircularProgress & keyof PeculiarCircularProgressAttributes as `prop:${K}`]?: PeculiarCircularProgress[K] };
        "peculiar-crl-viewer": Omit<PeculiarCrlViewer, keyof PeculiarCrlViewerAttributes> & { [K in keyof PeculiarCrlViewer & keyof PeculiarCrlViewerAttributes]?: PeculiarCrlViewer[K] } & { [K in keyof PeculiarCrlViewer & keyof PeculiarCrlViewerAttributes as `attr:${K}`]?: PeculiarCrlViewerAttributes[K] } & { [K in keyof PeculiarCrlViewer & keyof PeculiarCrlViewerAttributes as `prop:${K}`]?: PeculiarCrlViewer[K] };
        "peculiar-csr-viewer": Omit<PeculiarCsrViewer, keyof PeculiarCsrViewerAttributes> & { [K in keyof PeculiarCsrViewer & keyof PeculiarCsrViewerAttributes]?: PeculiarCsrViewer[K] } & { [K in keyof PeculiarCsrViewer & keyof PeculiarCsrViewerAttributes as `attr:${K}`]?: PeculiarCsrViewerAttributes[K] } & { [K in keyof PeculiarCsrViewer & keyof PeculiarCsrViewerAttributes as `prop:${K}`]?: PeculiarCsrViewer[K] };
        "peculiar-highlight-words": Omit<PeculiarHighlightWords, keyof PeculiarHighlightWordsAttributes> & { [K in keyof PeculiarHighlightWords & keyof PeculiarHighlightWordsAttributes]?: PeculiarHighlightWords[K] } & { [K in keyof PeculiarHighlightWords & keyof PeculiarHighlightWordsAttributes as `attr:${K}`]?: PeculiarHighlightWordsAttributes[K] } & { [K in keyof PeculiarHighlightWords & keyof PeculiarHighlightWordsAttributes as `prop:${K}`]?: PeculiarHighlightWords[K] };
        "peculiar-ssh-certificate-viewer": Omit<PeculiarSshCertificateViewer, keyof PeculiarSshCertificateViewerAttributes> & { [K in keyof PeculiarSshCertificateViewer & keyof PeculiarSshCertificateViewerAttributes]?: PeculiarSshCertificateViewer[K] } & { [K in keyof PeculiarSshCertificateViewer & keyof PeculiarSshCertificateViewerAttributes as `attr:${K}`]?: PeculiarSshCertificateViewerAttributes[K] } & { [K in keyof PeculiarSshCertificateViewer & keyof PeculiarSshCertificateViewerAttributes as `prop:${K}`]?: PeculiarSshCertificateViewer[K] };
        "peculiar-text-hider": PeculiarTextHider;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "peculiar-attribute-certificate-viewer": LocalJSX.IntrinsicElements["peculiar-attribute-certificate-viewer"] & JSXBase.HTMLAttributes<HTMLPeculiarAttributeCertificateViewerElement>;
            "peculiar-button-menu": LocalJSX.IntrinsicElements["peculiar-button-menu"] & JSXBase.HTMLAttributes<HTMLPeculiarButtonMenuElement>;
            "peculiar-certificate-chain-viewer": LocalJSX.IntrinsicElements["peculiar-certificate-chain-viewer"] & JSXBase.HTMLAttributes<HTMLPeculiarCertificateChainViewerElement>;
            "peculiar-certificate-decoder": LocalJSX.IntrinsicElements["peculiar-certificate-decoder"] & JSXBase.HTMLAttributes<HTMLPeculiarCertificateDecoderElement>;
            "peculiar-certificate-viewer": LocalJSX.IntrinsicElements["peculiar-certificate-viewer"] & JSXBase.HTMLAttributes<HTMLPeculiarCertificateViewerElement>;
            "peculiar-certificates-viewer": LocalJSX.IntrinsicElements["peculiar-certificates-viewer"] & JSXBase.HTMLAttributes<HTMLPeculiarCertificatesViewerElement>;
            "peculiar-circular-progress": LocalJSX.IntrinsicElements["peculiar-circular-progress"] & JSXBase.HTMLAttributes<HTMLPeculiarCircularProgressElement>;
            "peculiar-crl-viewer": LocalJSX.IntrinsicElements["peculiar-crl-viewer"] & JSXBase.HTMLAttributes<HTMLPeculiarCrlViewerElement>;
            "peculiar-csr-viewer": LocalJSX.IntrinsicElements["peculiar-csr-viewer"] & JSXBase.HTMLAttributes<HTMLPeculiarCsrViewerElement>;
            "peculiar-highlight-words": LocalJSX.IntrinsicElements["peculiar-highlight-words"] & JSXBase.HTMLAttributes<HTMLPeculiarHighlightWordsElement>;
            "peculiar-ssh-certificate-viewer": LocalJSX.IntrinsicElements["peculiar-ssh-certificate-viewer"] & JSXBase.HTMLAttributes<HTMLPeculiarSshCertificateViewerElement>;
            "peculiar-text-hider": LocalJSX.IntrinsicElements["peculiar-text-hider"] & JSXBase.HTMLAttributes<HTMLPeculiarTextHiderElement>;
        }
    }
}
